pipeline {
  agent {
    docker { image 'node:16-alpine' }
  }
  stages {
    stage('Test') {
      steps {
        sh 'hostname'
        sh 'docker --version'
        sh 'node --version'
      }
    }
  }
}
